version: '3.8'

services:
  # Backend Node.js Express API
  backend:
    container_name: backend
    image: logeshloki585/shopifyq:v1
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - FIREBASE_API_KEY=AIzaSyB_cR12fO4TPGPOFk88ZYQQlgxGoY2Ih4w
      - FIREBASE_AUTH_DOMAIN=bookmyshow-c8176.firebaseapp.com
      - FIREBASE_PROJECT_ID=bookmyshow-c8176
      - FIREBASE_STORAGE_BUCKET=bookmyshow-c8176.firebasestorage.app
      - FIREBASE_MESSAGING_SENDER_ID=147565784614
      - FIREBASE_APP_ID=1:147565784614:web:1f09dface52d8be34400e7
      - FIREBASE_MEASUREMENT_ID=G-9WNK56SW5J
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - shopifyq-network

  # Frontend Vite React App
  frontend:
    container_name: frontend
    image: logeshloki585/shopifyq-main:v1.1
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - VITE_SHOPIFY_API_KEY=${VITE_SHOPIFY_API_KEY}
      - VITE_SHOPIFY_API_SECRET=${VITE_SHOPIFY_API_SECRET}
      - VITE_REDIRECT_URI=${VITE_REDIRECT_URI}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - SUPABASE_ACCESS_TOKEN=${SUPABASE_ACCESS_TOKEN}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - VITE_STRIPE_WEBHOOK_SECRET=whsec_1991adb496c4528c9d6b64a6690ccfc1635845fbb9f0d1a0b47c18c02c9c0cb3
      - VITE_BACKEND_ENDPOINT=http://backend:3000/api
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - shopifyq-network

networks:
  shopifyq-network:
    driver: bridge
