version: '3.8'

services:
  shopifyq-app:
    container_name: shopy
    image: shopy
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - VITE_SHOPIFY_API_KEY=${VITE_SHOPIFY_API_KEY}
      - VITE_SHOPIFY_API_SECRET=${VITE_SHOPIFY_API_SECRET}
      - VITE_REDIRECT_URI=${VITE_REDIRECT_URI}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - SUPABASE_ACCESS_TOKEN=${SUPABASE_ACCESS_TOKEN}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - VITE_STRIPE_WEBHOOK_SECRET=whsec_1991adb496c4528c9d6b64a6690ccfc1635845fbb9f0d1a0b47c18c02c9c0cb3
      - VITE_BACKEND_ENDPOINT=http://localhost:3001/api
    restart: unless-stopped
    volumes:
      # For development/debugging purposes - uncomment if needed
      # - ./api:/app/api
      # - ./src/api:/app/src/api
      - ./logs:/app/logs
    networks:
      - shopifyq-network
    # Uncomment if you need healthcheck
    # healthcheck:
    #   test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s

networks:
  shopifyq-network:
    driver: bridge